import * as XLSX from 'xlsx';

const BRAND = {
  primary: '#0D7C4D',
  accent: '#1B8FBF',
  lightBg: '#E8F5EE',
  white: '#FFFFFF',
  textDark: '#0A2E1F',
  border: '#C8DCC8',
};

const LOGO_URL = 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/699fd59568d76f4dc3bcc93b/a9193cd52_logo.jpg';

function formatLabel(key) {
  return key.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
}

function cleanValue(value) {
  if (value === null || value === undefined) return '';
  if (typeof value === 'object') return JSON.stringify(value);
  return value;
}

function escapeHtml(value) {
  if (value === null || value === undefined) return '';
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

async function fetchLogoBase64() {
  try {
    const res = await fetch(LOGO_URL);
    const blob = await res.blob();
    return await new Promise((resolve) => {
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result);
      reader.onerror = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

function buildHeaderRow(keys) {
  return keys.map(k =>
    `<th style="background-color:${BRAND.primary};color:${BRAND.white};font-weight:bold;font-size:12px;border:1px solid ${BRAND.primary};text-align:left;white-space:nowrap;padding:8px 10px;font-family:'Segoe UI',Arial,sans-serif;">${escapeHtml(formatLabel(k))}</th>`
  ).join('');
}

function buildDataRows(cleaned, keys) {
  return cleaned.map((row, i) => {
    const bg = i % 2 === 0 ? BRAND.white : BRAND.lightBg;
    const cells = keys.map(k => {
      const val = row[k];
      const isLong = String(val).length > 50;
      return `<td style="background-color:${bg};color:${BRAND.textDark};font-size:11px;border:1px solid ${BRAND.border};${isLong ? 'white-space:normal;max-width:400px;' : 'white-space:nowrap;'}padding:6px 10px;font-family:'Segoe UI',Arial,sans-serif;">${escapeHtml(val)}</td>`;
    }).join('');
    return `<tr>${cells}</tr>`;
  }).join('');
}

function buildBrandHeader(logoBase64, subtitle, colspan) {
  const logoHtml = logoBase64
    ? `<img src="${logoBase64}" height="48" style="height:48px;vertical-align:middle;margin-right:10px;" />`
    : '';
  return `<tr>
    <td colspan="${colspan}" style="background-color:${BRAND.primary};color:${BRAND.white};font-size:22px;font-weight:bold;padding:14px 16px;vertical-align:middle;font-family:'Segoe UI',Arial,sans-serif;">${logoHtml}AQUAWOOD</td>
  </tr>
  <tr>
    <td colspan="${colspan}" style="background-color:${BRAND.accent};color:${BRAND.white};font-size:12px;padding:6px 16px;font-family:'Segoe UI',Arial,sans-serif;">${escapeHtml(subtitle)}</td>
  </tr>
  <tr><td colspan="${colspan}" style="height:10px;line-height:10px;">&nbsp;</td></tr>`;
}

function buildFooter(colspan) {
  return `<tr><td colspan="${colspan}" style="height:6px;">&nbsp;</td></tr>
  <tr><td colspan="${colspan}" style="color:${BRAND.primary};font-size:10px;font-style:italic;padding:4px 10px;font-family:'Segoe UI',Arial,sans-serif;">Generated by AQUAWOOD Environmental Monitoring System &middot; ${new Date().toLocaleString()}</td></tr>`;
}

function downloadHtmlAsExcel(html, filename) {
  const blob = new Blob(['\uFEFF' + html], { type: 'application/vnd.ms-excel;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename.replace('.xlsx', '.xls');
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export async function exportToExcel(data, filename, sheetName = 'Data') {
  const cleaned = data.map(row => {
    const clean = {};
    Object.entries(row).forEach(([key, value]) => { clean[key] = cleanValue(value); });
    return clean;
  });

  if (!cleaned.length) return;

  const keys = Object.keys(cleaned[0]);
  const logoBase64 = await fetchLogoBase64();
  const dateStr = new Date().toLocaleDateString('en-GB', { year: 'numeric', month: 'long', day: 'numeric' });

  const html = `<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head><meta charset="UTF-8">
<!--[if gte mso 9]><xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet><x:Name>${escapeHtml(sheetName.substring(0, 31))}</x:Name><x:WorksheetOptions><x:DisplayGridlines/></x:WorksheetOptions></x:ExcelWorksheet></x:ExcelWorksheets></x:ExcelWorkbook></xml><![endif]-->
</head>
<body>
<table border="0" cellspacing="0" cellpadding="0" style="font-family:'Segoe UI',Arial,sans-serif;">
${buildBrandHeader(logoBase64, `Group Uganda Limited \u00B7 ${sheetName} Export \u00B7 ${dateStr}`, keys.length)}
<tr>${buildHeaderRow(keys)}</tr>
${buildDataRows(cleaned, keys)}
${buildFooter(keys.length)}
</table>
</body>
</html>`;

  downloadHtmlAsExcel(html, filename);
}

export async function exportAllToExcel(entityDataMap, filename) {
  const entries = Object.entries(entityDataMap).filter(([, data]) => data && data.length > 0);
  if (!entries.length) return;

  const logoBase64 = await fetchLogoBase64();
  const dateStr = new Date().toLocaleDateString('en-GB', { year: 'numeric', month: 'long', day: 'numeric' });

  const sections = entries.map(([entityName, data]) => {
    const cleaned = data.map(row => {
      const clean = {};
      Object.entries(row).forEach(([key, value]) => { clean[key] = cleanValue(value); });
      return clean;
    });
    const keys = Object.keys(cleaned[0]);
    return `<table border="0" cellspacing="0" cellpadding="0" style="font-family:'Segoe UI',Arial,sans-serif;margin-bottom:16px;">
<tr><td colspan="${keys.length}" style="background-color:${BRAND.accent};color:${BRAND.white};font-size:14px;font-weight:bold;padding:10px 16px;font-family:'Segoe UI',Arial,sans-serif;">${escapeHtml(formatLabel(entityName))} (${cleaned.length} records)</td></tr>
<tr>${buildHeaderRow(keys)}</tr>
${buildDataRows(cleaned, keys)}
</table>`;
  }).join('');

  const maxCols = Math.max(...entries.map(([, data]) => Object.keys(data[0]).length));

  const html = `<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head><meta charset="UTF-8">
<!--[if gte mso 9]><xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet><x:Name>Full Backup</x:Name><x:WorksheetOptions><x:DisplayGridlines/></x:WorksheetOptions></x:ExcelWorksheet></x:ExcelWorksheets></x:ExcelWorkbook></xml><![endif]-->
</head>
<body>
<table border="0" cellspacing="0" cellpadding="0" style="font-family:'Segoe UI',Arial,sans-serif;">
${buildBrandHeader(logoBase64, `Group Uganda Limited \u00B7 Full Database Backup \u00B7 ${dateStr}`, maxCols)}
${buildFooter(maxCols)}
</table>
${sections}
</body>
</html>`;

  downloadHtmlAsExcel(html, filename);
}

export function parseExcelFile(file) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = (e) => {
      try {
        const data = new Uint8Array(e.target.result);
        const wb = XLSX.read(data, { type: 'array' });
        const ws = wb.Sheets[wb.SheetNames[0]];
        const json = XLSX.utils.sheet_to_json(ws, { defval: null });
        resolve(json);
      } catch (err) {
        reject(err);
      }
    };
    reader.onerror = reject;
    reader.readAsArrayBuffer(file);
  });
}